new/app/urls.py
from django.urls import path
from .views import *

app_name = "app"
urlpatterns = [
    path("", home, name="home")
]

new/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

new/app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class MyUser(AbstractUser):
    class Meta:
        verbose_name  = "My Users"
        verbose_name_plural = "My Users"
    
class Post(models.Model):
    title = models.CharField(max_length=150)
    category = models.ForeignKey('Category',blank=True, on_delete=models.CASCADE)
    def __str__(self):
        return self.title


class Category(models.Model):
    category_name = models.CharField(max_length=100)
    def __str__(self):
        return self.category_name

new/app/views.py
from django.shortcuts import render
from .models import *

def home(request):
    categories = request.GET.get("category")
    if categories == None:
        post = Post.objects.all()
    else:
        post = Post.objects.filter(category__category_name=categories)
        
    context = {
        "category":Category.objects.all()
        "post":post
    }
    return render(request, 'index.html', context)

new/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>category</title>
</head>
<body>
    <style>
        a{
            padding: 10px;
        }
    </style>
    <a href="{% url 'app:home' %}">All</a>
    {% for y in category %}
    <a href="{% url 'app:home' %}?category={{ y.category_name }}">{{ y.category_name }}</a>
    {% endfor %} 
    {% for x in post %}
    <h1>{{ x.title }}</h1>
    {% endfor %}
</body>
</html>